version: '3.8'

services:
  db:
      image: postgres:15-alpine
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=password1234
        - POSTGRES_DB=golang
      ports:
        - "5432:5432"
      volumes:
      - db_data:/var/lib/postgresql/data
      - ./golang.sql:/docker-entrypoint-initdb.d/golang.sql

  grpc_server:
    build: .
    depends_on:
      - db
    ports:
      - "33341:33341"
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password1234
      DB_NAME: golang

volumes:
  db_data: